name: pharo
version: 1.0.0
summary: Pharo 6 Smalltalk
description: |
    This package contains the 6.0 stable VM and image.
    
    Available commands:
        pharo runs the vm in headless mode.
        pharo.ui runs the vm with display.
        pharo.newvm copies the image and changes file to the working directory.
        pharo.sqlite3 runs the sqlite3 command line utility.
grade: devel
confinement: devmode

apps:
  pharo:
    command: usr/bin/pharo
    plugs: [home, unity7, opengl, network, x11]
  ui:
    command: usr/bin/pharo-ui
    plugs: [home, unity7, opengl, network, x11]
  sqlite3:
    command: usr/bin/sqlite3
    plugs: [home]
  newvm:
    command: usr/bin/newvm
    plugs: [home]


parts:
  pharo:
    source: ./
    plugin: make

  xdg-open:
    plugin: autotools
    source: https://github.com/snapcore/snapd-xdg-open.git
    source-type: git
    build-packages:
      - curl
      - unzip
      - libglib2.0-dev
    stage-packages:
        - gcc-multilib
        - libx11-6:i386
        - libgl1-mesa-glx:i386
        - libfontconfig1:i386
        - libssl1.0.0:i386
        - libcairo2-dev:i386
        - libc6-i386
        - libexpat1:i386
        - libgnome2-bin
        - xdg-utils
        - sqlite3
        - libsqlite3-dev:i386
        - git
