name: pharo
version: 1.3.1
summary: Pharo 6 Smalltalk
description: |
    This package contains the 6.0 threaded VM and image.
    
    Available commands:
        pharo runs the vm in headless mode.
        pharo.ui runs the vm with display.
        pharo.cleanimage copies the image and changes file to the working directory.
        pharo.getimage copies the latest 6.0 VM from http://get.pharo.org
        pharo.sqlite3 runs the sqlite3 command line utility.
        pharo.config configures system thread priority, see below.
    System Configuration:
        This Pharo VM uses a threaded heartbeat that requires elevated priority.
        Permission is granted by creating /etc/security/limits.d/pharo.conf
        with the appropriate contents.  Running pharo.config will create or
        overwrite the configuration file.  This command must be run as root:
        $ sudo pharo.config
        This command only needs to be run once, and you must log out and 
        back in for the changes to take effect.
    Web Site:
        The Pharo web site: http://pharo.org/
        Snapcraft package source: https://github.com/akgrant43/pharo-snap
grade: devel
confinement: classic

apps:
  pharo:
    command: bin/desktop-launch $SNAP/usr/bin/pharo
  ui:
    command: bin/desktop-launch $SNAP/usr/bin/pharo-ui
  sqlite3:
    command: usr/bin/sqlite3
  cleanimage:
    command: usr/bin/cleanimage
  getimage:
    command: usr/bin/getimage
  config:
    command: usr/bin/CONFIG


parts:
  pharo:
    source: ./
    plugin: make
    after:
        - desktop-glib-only

  xdg-open:
    plugin: autotools
    source: https://github.com/snapcore/snapd-xdg-open.git
    source-type: git
    build-packages:
      - ack-grep
      - autoconf
      - automake
      - bash-completion
      - build-essential
      - cmake
      - debhelper
      - devscripts
      - g++
      - gcc-multilib
      - git
      - libasound2-dev
      - libasound2-dev:i386
      - libasound2:i386
      - libasound2-plugins:i386
      - libc6-dev:i386
      - libfreetype6-dev
      - libfreetype6-dev:i386
      - libgl1-mesa-dev
      - libgl1-mesa-dev:i386
      - libgl1-mesa-glx:i386
      - libglapi-mesa:i386
      - libglib2.0-dev
      - libice-dev:i386
      - libsm-dev:i386
      - libssh2-1-dev
      - libssl1.0.0:i386
      - libssl-dev
      - libssl-dev:i386
      - libtool
      - libx11-dev
      - libx11-dev:i386
      - libxext-dev
      - libxext-dev:i386
      - locales-all
      - openssh-server
      - patchelf
      - ruby
      - unzip
      - uuid-dev
      - uuid-dev:i386
      - xz-utils
      - zip
    stage-packages:
      - gcc-multilib
      - libc-bin:i386
      - libx11-6:i386
      - libgl1-mesa-glx:i386
      - libfontconfig1:i386
      - libssl1.0.0:i386
      - libcairo2-dev:i386
      - libc6:i386
      - libexpat1:i386
      - libgnome2-bin
      - libasound2:i386
      - libasound2-dev:i386
      - libasound2-plugins:i386
      - libssl-dev:i386
      - libfreetype6-dev:i386
      - libsm-dev:i386
      - libice-dev:i386
      - libgl1-mesa-dev:i386
      - libxext-dev:i386
      - libglapi-mesa:i386
      - uuid-dev:i386
      - sqlite3
      - libsqlite3-dev:i386
      - git
      - vim
      - curl
      - unzip
      - locales-all

