#!/bin/bash
# Download the latest image and changes file to the users working directory

wget http://files.pharo.org/image/60/latest-64.zip
unzip latest-64.zip
mv Pharo64-6*.image Pharo.image
mv Pharo64-6*.changes Pharo.changes
rm latest-64.zip

